import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { AuthServiceService } from '../auth-service.service';
import { Router } from '@angular/router';
import { waves_template, schedules, hires_template, periods, payments, Fecha, formerEmployer } from '../process_templates'
import { employees, payment_methods } from '../fullProcess';
import { THIS_EXPR } from '@angular/compiler/src/output/output_ast';
import { isNull, isNullOrUndefined } from 'util';

@Component({
  selector: 'app-accdashboard',
  templateUrl: './accdashboard.component.html',
  styleUrls: ['./accdashboard.component.css']
})
export class AccdashboardComponent implements OnInit {

  waves: waves_template[] = [new waves_template];
  wave_ToEdit: waves_template = new waves_template;
  schedules: schedules[] = [new schedules];
  schedule_to_edit: schedules = new schedules;
  hires: hires_template[] = [];
  employees: employees[] = [];
  includeAll: boolean = false;
  periods: periods[] = [];
  actualPeriod: periods = new periods;
  filter: string = null;
  value: string = null;
  searching: boolean = false;
  edit_bank: boolean = false;
  isformerEmployer: boolean = false;
  formerEmployer: formerEmployer[] = [];
  waveFormerEmployer: formerEmployer[] = [];
  actualFormerEmployer: formerEmployer = new formerEmployer;
  stateFormerEmployer: string = 'Browser';

  constructor(private apiService: ApiService, public router: Router, private authSrv: AuthServiceService) { }

  ngOnInit() {
    this.getFormerEmployer();
    this.getWavesAll();
    this.getPeriods();
    this.getAllEmployees();
  }

  getPeriods() {
    this.apiService.getPeriods().subscribe((prd: periods[]) => {      
      prd.forEach(per => {        
        if (per.status=='0'){
          per.status = 'CLOSED';
        } else if (per.status=='1') {
          per.status = 'OPEN';
          this.actualPeriod = per;
        }else if(per.status == '3'){
          per.status = 'FROZEN';
        }
      })
      this.periods = prd;
    });
  }

  getAllEmployees() {
    this.apiService.getallEmployees({ department: 'all' }).subscribe((emp: employees[]) => {
      this.employees = emp;
    })
  }

  searchEmployee() {
    this.searching = true;
    this.apiService.getSearchEmployees({ filter: this.filter, value: this.value, dp: 'all' }).subscribe((emp: employees[]) => {
      this.employees = emp;
    })
  }

  gotoProfile(emp: employees) {
    this.router.navigate(['./accProfile', emp.idemployees]);
  }

  cancelSearch() {
    this.getWavesAll();
    this.getPeriods();
    this.getAllEmployees();
    this.searching = false;
  }

  gotoPeriod(id: string) {
    this.router.navigate(['./periods', id]);
  }

  editBank() {
    this.edit_bank = true;
  }

  finishEdit() {
    this.hires.forEach(hire => {
      if (hire.status == 'EMPLOYEE') {
        this.apiService.updateBank(hire).subscribe((str: string) => {
        });
      }
      this.hideSchedules();
      this.getWavesAll();
      this.getPeriods();
      this.getAllEmployees();
    })
  }

  completeWave() {
    let pay: payments = new payments;    
    this.hires.forEach(hire => {
      if (hire.status == 'EMPLOYEE') {
        if (parseFloat(hire.account) > 0) {
          let paymentMethod: payment_methods = new payment_methods;
          this.apiService.getSearchEmployees({ filter: 'id_profile', value: hire.id_profile, dp: 'all' }).subscribe((emp: employees[]) => {
            let date: Fecha = new Fecha;

            paymentMethod.type = "BANK ACCOUNT";
            paymentMethod.bank = hire.bank;
            paymentMethod.number = hire.account;
            paymentMethod.predeterm = '1';
            paymentMethod.id_user = this.authSrv.autUser.iduser;
            paymentMethod.id_employee = emp[0].idemployees;
            paymentMethod.date = date.today;
            paymentMethod.notes = 'Generated by the system automatically.';
            this.apiService.insertPaymentMethod(paymentMethod).subscribe((str: string) => {
              if (String(str).split("|")[0] !="0") {
                pay.id_employee = emp[0].idemployees;
                pay.id_paymentmethod = str;
                pay.id_period = this.actualPeriod.idperiods;
                pay.last_seventh = '0.00';
                pay.credits = '0.00';
                pay.debits = '0.00';
                pay.base = '0.00';
                pay.productivity = '0.00';
                pay.base_complete = emp[0].base_payment;
                pay.productivity_complete = emp[0].productivity_payment;
                pay.client_id = emp[0].client_id;
                pay.id_account_py = emp[0].id_account;
                this.apiService.insertPayments(pay).subscribe((str: string) => {
                  if (str=="1"){
                    this.ngOnInit();
                  } else {
                    window.alert("An error has occured:\n" + str.split("|")[0] + "\n" + str.split("|")[1]);
                  }
                })                     
              } else  {
                window.alert("An error has occured:\n" + str.split("|")[1] + "\n" + str.split("|")[2]);
              }
            })
          })
        }
      }
    })
    this.hideSchedules();    
    this.getWavesAll();
    this.getPeriods();
    this.getAllEmployees();
    this.cancelEdit();
  }

  getWavesAll() {
    this.waves = [];
    const date = ">=" + new Date().getFullYear() + "-" + (new Date().getMonth() + 1) + "-" + new Date().getDate();
    this.apiService.getfilteredWaves({ str: date }).subscribe((readWaves: waves_template[]) => {
      this.wave_ToEdit = readWaves[0];
      readWaves.forEach(wv=>{
        wv.state = wv.state.split(",")[0];
          if(wv.state == '0'){
            this.waves.push(wv);
          }
        })
      })
  }

  editW(wv: waves_template) {
    const date = ">=" + new Date().getFullYear() + "-" + (new Date().getMonth() + 1) + "-" + new Date().getDate();
    this.apiService.getfilteredWaves({ str: date }).subscribe((readWaves: waves_template[]) => {
      readWaves.forEach(ww=>{
        if(ww.idwaves == wv.idwaves){
          wv.state = wv.state + "," + ww.state.split(",")[1] + "," + ww.state.split(",")[2] + "," + ww.state.split(",")[3];
        }
      })
      this.apiService.updateWaveState(wv).subscribe((st: string) => {
        this.getWavesAll();
        this.getPeriods();
        this.getAllEmployees();
        this.hideSchedules();
      });
    })
  }


  getSchedules(wv: waves_template) {
    this.hires = [];
    this.waves.forEach(wa => {
      wa.show = '0';
    });
    this.apiService.getFilteredHires(wv).subscribe((hires: hires_template[]) => {
      this.waveFormerEmployer = [];
      hires.forEach(hire => {
        this.apiService.getSearchEmployees({dp:'all', filter:'id_profile', value:hire.id_profile}).subscribe((emp:employees[])=>{
          this.apiService.getPaymentMethods(emp[0]).subscribe((pym:payment_methods[])=>{
            if(isNull(pym)){
              hire.bool = false;
            }else{
              if(pym.length>0){
                hire.bool = true;
              }else{
                hire.bool = false;
              }
            }
            this.hires.push(hire);
            this.filteredFormerEmployer(emp);
          })
        })
      });
    });
    this.waves[this.waves.indexOf(wv)].show = "1";
  }

  hideSchedules() {
    this.waves.forEach(w => {
      w.show = '0';
    })
  }

  cancelEdit() {
    this.edit_bank = false;
    this.hideSchedules();
    this.getWavesAll();
    this.getPeriods();
    this.getAllEmployees();
  }

  insertFormerEmployer() {
    this.apiService.insertFormerEmployer(this.actualFormerEmployer).subscribe((_str: string) => { 
    //
    })
  }

  getFormerEmployer() {
    this.apiService.getFormerEmployer().subscribe((str: formerEmployer[]) => { 
      this.formerEmployer = str;
    })
  }

  updateFormerEmployer() {
    this.apiService.updateFormerEmployer(this.actualFormerEmployer).subscribe((_str: string) => { 
      //
      })
  }

  saveFormerEmployer(){
    this.waveFormerEmployer.forEach(emp => {
      this.actualFormerEmployer = emp;
      if (emp.idformer_employes == null) {
        if (!(((this.actualFormerEmployer.idemnization == '') && (this.actualFormerEmployer.aguinaldo == '') && 
        (this.actualFormerEmployer.bono14 == '') && (this.actualFormerEmployer.igss == '') 
        && (this.actualFormerEmployer.taxpendingpayment == '')) || ((this.actualFormerEmployer.idemnization == null) && (this.actualFormerEmployer.aguinaldo == null) && 
        (this.actualFormerEmployer.bono14 == null) && (this.actualFormerEmployer.igss == null) 
        && (this.actualFormerEmployer.taxpendingpayment == null)))) {
          this.insertFormerEmployer();
        }
      } else {
        this.updateFormerEmployer();
      }
    })
    this.stateFormerEmployer = 'Browser';
    this.isformerEmployer = false;
    this.ngOnInit();
  }

  editFormerEmployer() {
    this.isformerEmployer = true;
    this.stateFormerEmployer = 'Edit';
  }

  showFormerEmployer() {
    this.isformerEmployer = true;
    this.stateFormerEmployer = 'Browser';
  }

  delFormerEmployer() {
    this.apiService.deleteFormerEmployer(this.actualFormerEmployer).subscribe((str: string) => {
      if ((isNullOrUndefined(str) == true) || (str==''))
        window.alert('former employer successfully removed.');
    })
  }

  cancelFormerEmployer(){
    this.isformerEmployer = false;
    this.stateFormerEmployer = 'Browser';
  }

  filteredFormerEmployer(femp: employees[]) {
    let filterFE: formerEmployer[] = [];
    femp.forEach(emp => {
      filterFE = this.formerEmployer.filter(fe => fe.id_employee == emp.idemployees);
      if (filterFE.length > 0) {
        this.waveFormerEmployer.push(filterFE[0]);
      } else {
        this.actualFormerEmployer = new formerEmployer;
        this.actualFormerEmployer.id_employee = emp.idemployees;
        this.actualFormerEmployer.name = emp.name;
        this.waveFormerEmployer.push(this.actualFormerEmployer);
      }
    })
  }
}
