export class profiles {
    idprofiles: string;
    tittle: string;
    first_name: string;
    second_name: string;
    first_lastname: string;
    second_lastname: string;
    day_of_birth: string;
    nationality: string;
    gender:string;
    etnia:string;
    bank:string;
    account:string;    
    account_type:string;  
    marital_status: string;
    dpi: string;
    nit: string;
    iggs: string;
    irtra: string;
    status: string;
    idcontact_details: string;
    id_profile: string;
    primary_phone: string;
    secondary_phone: string;
    address: string;
    city: string;
    email: string;
    idjob_histories: string;
    company: string;
    date_joining: string;
    date_end: string;
    position: string;
    reference_name: string;
    reference_lastname: string;
    reference_position: string;
    reference_email: string;
    reference_phone: string;
    working: string;
    idprofile_details: string;
    english_level: string;
    transport: string;
    start_date: string;
    unavialable_days: string;
    marketing_campaing: string;
    first_lenguage: string;
    second_lenguage: string;
    third_lenguage: string;
    idemergency_details: string;
    emergency_first_name: string;
    emergency_second_name: string;
    emergency_first_lastname: string;
    emergency_second_lastname: string;
    phone: string;
    relationship: string;
    idmedical_details: string;
    medical_treatment: string;
    medical_prescription: string;
    ideducation_details: string;
    current_level: string;
    further_education: string;
    currently_studing: string;
    institution_name: string;
    degree: string;
    iddocuments: string;
    doc_type: string;
    doc_path: string;
}

export class profiles_histories{
    idjob_histories: string;
    company: string;
    date_joining: string;
    date_end: string;
    position: string;
    reference_name: string;
    reference_lastname: string;
    reference_position: string;
    reference_email: string;
    reference_phone: string;
    working: string;
}

export class profiles_family{    
    idaffinity_details: number;    
    affinity_idfamilies: number;    
    affinity_id_profile: number;
    affinity_first_name: string;
    affinity_second_name: string;
    affinity_first_last_name: string;
    affinity_second_last_name: string;
    affinity_phone: string;
    affinity_relationship: string;
    affinity_birthdate: Date;
}